INSERT INTO public.datos_mamalones (tipo, titulo, contenido, mundial_anio, tags, contexto, prioridad, metadata) VALUES
('hito', 'La Mano de Dios (y la del siglo)', 'En México 86, Maradona anotó contra Inglaterra con la mano y minutos después hizo el gol considerado el del siglo. Un mismo partido, dos leyendas… y cero VAR.', 1986, ARRAY['argentina','inglaterra','maradona','controversia'], ARRAY['medio_tiempo','idle'], 10, '{"equipos":["ARG","ENG"]}'::jsonb),
('trivia', '¿Quién fue campeón en Sudáfrica 2010?', 'España ganó su primer Mundial. El gol de la final lo marcó Andrés Iniesta en prórroga contra Países Bajos.', 2010, ARRAY['españa','final','trivia'], ARRAY['idle','cualquiera'], 5, '{"respuesta":"España","opciones":["España","Holanda","Alemania","Brasil"]}'::jsonb),
('record', 'El Mundial más goleador', 'Catar 2022 ostenta el récord absoluto con 172 goles anotados en 64 partidos, superando por uno los torneos de Francia 1998 y Brasil 2014.', 2022, ARRAY['goles','record'], ARRAY['post_gol','idle'], 7, '{}'::jsonb),
('curiosidad', 'Zinedine Zidane y el cabezazo de Berlín', 'En la final de 2006, Zidane vio la roja por un cabezazo a Materazzi. Su último partido profesional terminó con una expulsión histórica.', 2006, ARRAY['francia','italia','final','roja'], ARRAY['medio_tiempo','idle'], 9, '{}'::jsonb),
('meme_historico', 'Brasil 7 - Alemania 1', 'Semifinal en casa, 2014. El Mineirão se quedó en un silencio sepulcral ante la mayor goleada recibida por la verdeamarela en su historia.', 2014, ARRAY['brasil','alemania','goleada'], ARRAY['post_gol','idle'], 10, '{}'::jsonb),
('hito', 'Corea del Sur 2002: la fiesta asiática', 'Corea llegó a semifinales siendo anfitriona, eliminando a Italia y España en partidos cargados de polémica arbitral.', 2002, ARRAY['corea','sorpresa'], ARRAY['idle'], 6, '{}'::jsonb),
('trivia', 'México: sede tres veces', 'México será el primer país en organizar tres Mundiales (1970, 1986 y 2026). En 70 y 86 también jugó el partido inaugural como local.', 2026, ARRAY['mexico','sede','trivia'], ARRAY['cualquiera','idle'], 8, '{"respuesta":"México","local":true}'::jsonb),
('curiosidad', 'Grosso y el penal de la gloria', 'Italia 2006: el lateral Fabio Grosso, que no era el cobrador habitual, pidió tirar el quinto penal definitivo de la tanda contra Francia para coronar a la Azzurra.', 2006, ARRAY['italia','penales','final'], ARRAY['idle','medio_tiempo'], 4, '{}'::jsonb),
('hito', 'Roger Milla y el baile en 1990', 'A los 38 años, Milla llevó a Camerún a cuartos de final y celebró cada gol con un icónico bailecito en el banderín de córner.', 1990, ARRAY['camerun','celebracion'], ARRAY['idle'], 5, '{}'::jsonb),
('record', 'Miroslav Klose, rey de goles', 'Con 16 goles en cuatro Mundiales, el alemán Klose superó el récord del "Fenómeno" Ronaldo Nazário precisamente jugando en Brasil 2014.', 2014, ARRAY['goleador','alemania','record'], ARRAY['post_gol','idle'], 6, '{}'::jsonb),
('curiosidad', 'El Mundial de los 13 invitados', 'En Uruguay 1930 sólo participaron 13 selecciones por invitación. Muchos equipos europeos se negaron a viajar dos semanas en barco.', 1930, ARRAY['uruguay','historia'], ARRAY['idle'], 3, '{}'::jsonb),
('meme_historico', 'El trauma de Bulgaria 94', 'México cayó en octavos contra Bulgaria en penales tras empatar 1-1. Quedó marcado por el golazo de Aspe y las mallas del arco rotas por Marcelino Bernal.', 1994, ARRAY['mexico','bulgaria','fail'], ARRAY['idle','post_gol'], 7, '{}'::jsonb),
('trivia', '¿Cuántas Copas tiene Brasil?', 'Brasil es el máximo ganador con 5 títulos (1958, 1962, 1970, 1994, 2002). Sigue siendo el único pentacampeón del planeta.', 2002, ARRAY['brasil','trivia','record'], ARRAY['cualquiera','idle'], 5, '{"respuesta":"5"}'::jsonb),
('hito', 'Paolo Rossi renace en España 82', 'Tras estar suspendido por un escándalo de apuestas, Rossi volvió para marcar un hat-trick histórico que eliminó al Brasil de Zico y dar el título a Italia.', 1982, ARRAY['italia','brasil','rossi'], ARRAY['idle','medio_tiempo'], 8, '{}'::jsonb),
('curiosidad', 'La compensación más larga', 'En Catar 2022, el partido Inglaterra vs Irán tuvo la compensación más larga en fase de grupos: casi 24 minutos añadidos en total debido a la conmoción del portero iraní.', 2022, ARRAY['lesion','arbitro'], ARRAY['medio_tiempo','idle'], 4, '{}'::jsonb)
;